global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'fanet-api'
    static_configs:
      - targets: ['app:8090']  # Devcontainer service name
        labels:
          service: 'fanet-api'
          environment: 'development'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Redis и MySQL exporters можно добавить при необходимости
  # - job_name: 'redis-exporter'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']
  # 
  # - job_name: 'mysql-exporter'
  #   static_configs:
  #     - targets: ['mysql-exporter:9104']