global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'fanet-api'
    static_configs:
      - targets: ['host.docker.internal:8090']  # Для Docker Desktop
        labels:
          service: 'fanet-api'
          environment: 'development'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'redis'
    static_configs:
      - targets: ['host.docker.internal:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s
    # Redis exporter можно добавить при необходимости

  - job_name: 'mysql'
    static_configs:
      - targets: ['host.docker.internal:3306']
    metrics_path: '/metrics'
    scrape_interval: 30s
    # MySQL exporter можно добавить при необходимости