version: '3.8'

services:
  fanet-api:
    build:
      context: ../..
      dockerfile: Dockerfile
    ports:
      - "8090:8090"  # API port
      - "9090:9090"  # Metrics port
    environment:
      - SERVER_PORT=8090
      - REDIS_URL=redis://redis:6379
      - MQTT_URL=tcp://mqtt:1883
      - MYSQL_DSN=root:password@tcp(mysql:3306)/fanet?parseTime=true
      - LOG_LEVEL=debug
      - LOG_FORMAT=text
    depends_on:
      - redis
      - mqtt
      - mysql
    volumes:
      - ../../:/app  # For development with air
    command: air  # Hot reload for development
    networks:
      - fanet-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - fanet-network

  mqtt:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"  # MQTT port
      - "9001:9001"  # WebSocket port
    volumes:
      - ./mosquitto-simple.conf:/mosquitto/config/mosquitto.conf
      - mqtt-data:/mosquitto/data
      - mqtt-logs:/mosquitto/log
    networks:
      - fanet-network

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=fanet
      - MYSQL_USER=fanet
      - MYSQL_PASSWORD=fanet
    volumes:
      - mysql-data:/var/lib/mysql
      - ../../ai-spec/database/legacy-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - fanet-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - fanet-network

  adminer:
    image: adminer
    ports:
      - "8082:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    depends_on:
      - mysql
    networks:
      - fanet-network

volumes:
  redis-data:
  mqtt-data:
  mqtt-logs:
  mysql-data:

networks:
  fanet-network:
    driver: bridge