apiVersion: v1
kind: Secret
metadata:
  name: fanet-secrets
  namespace: fanet
type: Opaque
stringData:
  # Production Redis (внешний управляемый сервис)
  REDIS_URL: "redis://prod-redis-cluster.flybeeper.com:6379"
  REDIS_PASSWORD: "CHANGE_ME_PRODUCTION_REDIS_PASSWORD"
  
  # Production MQTT Broker
  MQTT_URL: "tcp://prod-mqtt.flybeeper.com:1883"
  MQTT_USERNAME: "fanet-api-prod"
  MQTT_PASSWORD: "CHANGE_ME_PRODUCTION_MQTT_PASSWORD"
  
  # Production MySQL
  MYSQL_DSN: "fanet_user:CHANGE_ME_PRODUCTION_MYSQL_PASSWORD@tcp(prod-mysql.flybeeper.com:3306)/fanet_production?parseTime=true&charset=utf8mb4&collation=utf8mb4_unicode_ci&tls=true"
  
  # Production Laravel API
  AUTH_ENDPOINT: "https://api.flybeeper.com/api/v4/user"