apiVersion: v1
kind: Namespace
metadata:
  name: fanet
  labels:
    app.kubernetes.io/name: fanet-backend
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: flybeeper-platform
    app.kubernetes.io/version: "1.0.0"
    environment: production
  annotations:
    description: "FANET Backend API - высокопроизводительный Go backend для real-time отслеживания FANET устройств"
    maintainer: "flybeeper-dev-team"
    prometheus.io/scrape: "false"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: fanet-quota
  namespace: fanet
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    pods: "50"
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: fanet-limits
  namespace: fanet
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "250m"
      memory: "256Mi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim