apiVersion: v1
kind: Secret
metadata:
  name: fanet-secrets
  namespace: fanet
  labels:
    app.kubernetes.io/name: fanet-backend
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: flybeeper-platform
type: Opaque
stringData:
  # Redis URL with authentication
  REDIS_URL: "redis://redis-cluster.fanet.svc.cluster.local:6379"
  REDIS_PASSWORD: ""
  
  # MQTT Broker URL with authentication
  MQTT_URL: "tcp://mqtt-broker.fanet.svc.cluster.local:1883"
  MQTT_USERNAME: ""
  MQTT_PASSWORD: ""
  
  # MySQL DSN for batch writer
  MYSQL_DSN: "user:password@tcp(mysql.fanet.svc.cluster.local:3306)/fanet?parseTime=true&charset=utf8mb4&collation=utf8mb4_unicode_ci"
  
  # Laravel API endpoint for authentication
  AUTH_ENDPOINT: "https://api.flybeeper.com/api/v4/user"
---
apiVersion: v1
kind: Secret
metadata:
  name: fanet-secrets-external
  namespace: fanet
  labels:
    app.kubernetes.io/name: fanet-backend
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: flybeeper-platform
  annotations:
    description: "External services secrets for production deployment"
type: Opaque
stringData:
  # Production Redis URL (external managed service)
  REDIS_URL_EXTERNAL: "redis://redis-cluster.prod.flybeeper.com:6379"
  REDIS_PASSWORD_EXTERNAL: "CHANGE_ME_PRODUCTION_REDIS_PASSWORD"
  
  # Production MQTT Broker URL
  MQTT_URL_EXTERNAL: "tcp://mqtt.prod.flybeeper.com:1883"
  MQTT_USERNAME_EXTERNAL: "fanet-api-prod"
  MQTT_PASSWORD_EXTERNAL: "CHANGE_ME_PRODUCTION_MQTT_PASSWORD"
  
  # Production MySQL DSN
  MYSQL_DSN_EXTERNAL: "fanet_user:CHANGE_ME_PRODUCTION_MYSQL_PASSWORD@tcp(mysql.prod.flybeeper.com:3306)/fanet_production?parseTime=true&charset=utf8mb4&collation=utf8mb4_unicode_ci&tls=true"