apiVersion: v1
kind: Secret
metadata:
  name: fanet-secrets
  namespace: fanet-dev
type: Opaque
stringData:
  # Dev Redis (внутренний кластер)
  REDIS_URL: "redis://redis-cluster.fanet-dev.svc.cluster.local:6379"
  REDIS_PASSWORD: ""
  
  # Dev MQTT Broker (внутренний)
  MQTT_URL: "tcp://mqtt-broker.fanet-dev.svc.cluster.local:1883"
  MQTT_USERNAME: ""
  MQTT_PASSWORD: ""
  
  # Dev MySQL (внутренний или внешний dev)
  MYSQL_DSN: "root:devpassword@tcp(mysql.fanet-dev.svc.cluster.local:3306)/fanet_dev?parseTime=true&charset=utf8mb4"
  
  # Dev Laravel API (staging/dev endpoint)
  AUTH_ENDPOINT: "https://dev-api.flybeeper.com/api/v4/user"